title: "Event Store Documentation"
permalink: pretty
markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter: rouge
exclude:
    - node_modules
    - .git

top_level_sections:
    - Introduction
    - Server
    - .NET API
    - HTTP API
    - Projections

latest_versions:
    server: 4.0.2
    dotnet-api: 4.0.2
    http-api: 4.0.2
    introduction: 4.0.2
    projections: 4.0.2

# Collections
collections:
  current:
    output: true
    permalink: /:collection/:path
    version: current # Depending on your requirements, you may not need this variable. Also you may be able to default it using :collection, but I haven't tried that.
    title: Latest Release
  "4.0.2": # quoting version number to avoid the error: undefined method `gsub' for 4.1:Float
    output: true
    permalink: /:collection/:path
    version: "4.0.2"
    title: Release 4.0.2
  "4.0.0":
    output: true
    permalink: /:collection/:path
    version: "4.0.0"
    title: Release 4.0.0

all_versions:
    - 4.0.2
    - 4.0.0
    - 3.9.0
    - 3.8.1
    - 3.8.0
    - 3.7.0
    - 3.6.0
    - 3.5.0
    - 3.4.0
    - 3.3.0
    - 3.2.0
    - 3.1.0
    - 3.0.5
    - 3.0.3
    - 3.0.2
    - 3.0.1
    - 3.0.0

all_dotnet_versions:
    - 4.0.2
    - 4.0.0
    - 3.9.0
    - 3.8.0
    - 3.7.0
    - 3.6.0
    - 3.5.0
    - 3.4.0
    - 3.3.1
    - 3.2.0
    - 3.1.0
    - 3.0.2
    - 3.0.1
    - 3.0.0

defaults:
    -
        scope:
            path: ""
        values:
            exclude_from_sidebar: false
            layout: "docs"
            pinned: false
